<template>
  <v-bottom-navigation
    color="teal"
    grow
    fixed
    horizontal
  >
    <v-btn>
      <v-icon>mdi-heart-outline</v-icon>
    </v-btn>
    <v-btn>
      <v-icon>mdi-history</v-icon>
    </v-btn>

    <v-btn>
      <v-icon>mdi-map-marker</v-icon>
    </v-btn>
    <v-btn>
      <v-icon>mdi-map-marker</v-icon>
    </v-btn>
  </v-bottom-navigation>
</template>
